import 'package:flutter/material.dart';
String baseApiUrl="http://139.5.147.55:9999";

Color kPrimaryColor = Colors.yellow.shade800;
Color kSecondColor = Colors.yellow.shade50;

double kPrimaryFontSize = 15;
double kSecodFontSize = 12;

String kLifeCycle = "Life Cycle";
String kStack = "Stack";
String kImages = "Images";
String kFlex = "Flex";
String kRowsColumns = "Rows and Columns";
String kExpanded = "Expanded";
String kCard = "Card";
String kButton = "Button";
String kGridView = "GridView";
String kIntrinsic = "Intrinsic";
String kFormAndInput = "Form and input";
String kFutureBuilder = "FutureBuilder";
String kAnimation = "Animation";
String kScrolbarable = "Scrollbarable";
String kAppbarAndTab = "Appbar";
String kButtonNavigationBar = "ButtonNavigationBar";
String kTabbar = "Tabbar";
String kSilverAppBar = "SilverAppbar";
String kNavigator = "Navigator";
String kJsonRestFulWorkshop = "Json RestFul Feed Wokrshop";
String kStreamBuilder = "StreamBuilder";
String kPullToRefresh = "Pull To Refresh";
String kYoutubePlayer = "Youtube Player";
String kScanQrcode = "Scan Qrcode";
String kGenQrcode = "Generate Qrcode";
String kSqliteDatabase = "Sqlite Database";
String kProvider = "Provider";
String kBlocPattern = "Bloc Pattern";
String kStreamBuilderYield = "StreamBuilder Yield";
String kWidgetApp = "WidgetApp";
String kInputAndSelect = "Input And Select";
String kDialogAlertPanel = "Dialog Alert and Panel";
String kChip = "Chip";
String kLinearProgressIndicator = "Linear Progress Indicator";
String kDivider = "Divider";
String kStepper = "Stepper";
String kLogout = "Log out";
